name: flutter_native_image
description: A flutter plugin which uses native iOS/Android to resize, compress or crop
version: 0.0.6+1
homepage: https://konseben.dev
issue_tracker: https://github.com/btastic/flutter_native_image/issues
publish_to: https://dart.pkg.jetbrains.space/slingshotai/p/main/ashley-protos-dart/

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutternativeimage
        pluginClass: FlutterNativeImagePlugin
      ios:
        package: com.example.flutternativeimage
        pluginClass: FlutterNativeImagePlugin
